# Generated by Django 3.2.5 on 2021-12-18 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agri', '0008_auto_20211218_1842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='govempuser',
            name='Email',
        ),
        migrations.AddField(
            model_name='govempuser',
            name='EmployeeId',
            field=models.CharField(default=None, max_length=30, unique=True),
        ),
    ]
