# Generated by Django 4.0 on 2021-12-18 16:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agri', '0009_auto_20211218_1927'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('season', models.CharField(choices=[('Rabi', 'Rabi'), ('Kharif', 'Kharif'), ('Zaid', 'Zaid')], max_length=50)),
                ('state', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('arrivals', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('pesticides', models.CharField(max_length=100)),
                ('fertilizers', models.CharField(max_length=100)),
                ('seed', models.CharField(max_length=100)),
                ('soil_health', models.CharField(max_length=100)),
            ],
        ),
    ]
