# Generated by Django 4.0 on 2021-12-18 16:52

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('agri', '0010_crop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='season',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Rabi', 'Rabi'), ('Kharif', 'Kharif'), ('Zaid', 'Zaid')], max_length=50),
        ),
    ]
