# Generated by Django 4.0 on 2021-12-18 16:58

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('agri', '0011_alter_crop_season'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='state',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('TS', 'Telangana'), ('AP', 'AndhraPradesh'), ('TN', 'Tamilnaidu'), ('KA', 'Karnataka'), ('MH', 'Maharastra')], max_length=200),
        ),
    ]
