# Generated by Django 4.0 on 2021-12-18 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agri', '0015_alter_crop_crop_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crop',
            name='arrivals',
        ),
        migrations.AddField(
            model_name='crop',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
