# Generated by Django 4.0 on 2021-12-18 21:19

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('agri', '0018_alter_crop_climate_alter_crop_soil_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='state',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Telangana', 'Telangana'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Tamil Nadu', 'Tamil Nadu'), ('Karnataka', 'Karnataka'), ('Maharastra', 'Maharastra')], max_length=200),
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vurl', models.CharField(max_length=150)),
                ('desciption', models.CharField(max_length=1500)),
                ('doc', models.FileField(default=None, upload_to='images/')),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='agri.crop')),
            ],
        ),
    ]
