# Generated by Django 4.0 on 2021-12-18 21:24

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('agri', '0019_alter_crop_state_training'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='state',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Telangana', 'Telangana'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Tamil Nadu', 'Tamil Nadu'), ('Karnataka', 'Karnataka'), ('Maharastra', 'Maharastra')], max_length=200),
        ),
    ]
