# Generated by Django 4.0 on 2021-12-18 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agri', '0019_alter_crop_state_training'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crop',
            name='state',
        ),
    ]
