# Generated by Django 4.0 on 2021-12-19 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agri', '0020_alter_crop_state'),
        ('agri', '0020_remove_crop_state'),
    ]

    operations = [
    ]
