# Generated by Django 4.0 on 2021-12-19 02:01

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('agri', '0021_merge_0020_alter_crop_state_0020_remove_crop_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublishUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('story', models.CharField(max_length=5000)),
                ('author', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='crop',
            name='state',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Telangana', 'Telangana'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Tamil Nadu', 'Tamil Nadu'), ('Karnataka', 'Karnataka'), ('Maharastra', 'Maharastra')], default='Telangana', max_length=200),
        ),
        migrations.CreateModel(
            name='BlogContent11',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('story', models.CharField(max_length=5000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories', to='auth.user')),
            ],
        ),
    ]
