# Generated by Django 4.0 on 2021-12-19 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agri', '0022_publishuser_alter_crop_state_blogcontent11'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcontent11',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
